task03-telegram_bot, Кравченко Дмитрий, 4й курс
equivalence1/scala-2017 pull request #3
Opened 2017-10-01 23:38 UTC by equivalence1

2017-10-02 05:47 UTC, adkozlov commented
Добавьте, пожалуйста, @dzharkov в качестве ревьюера.

2017-10-07 10:21 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы 10.10 23:59. Не забудь написать “@dzharkov” в комменте к PR

2017-10-07 10:21 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/task03/bot/TwitchNotifyBot.scala
> +          reply(s"'$name' channel has been successfully removed from your list")
Нужна валидация, что такой канал был в базе

2017-10-07 10:21 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/task03/bot/TwitchNotifyBot.scala
> +        case Success(ChannelsList(list)) => reply(list.toBuffer.mkString("\n"))
Зачем здесь `.toBuffer`?

2017-10-07 12:00 UTC, equivalence1 commented
@dzharkov 
Fixed

2017-10-14 12:09 UTC, dzharkov approved these changes
Ок, 5/10

2017-11-29 21:28 UTC, closed without merging